library(xlsx)
bodyfatdata<-read.xlsx("C:/Users/AvonPrende/Desktop/Project/bodyfatdata.xlsx",1)
percentageFat<-bodyfatdata$percentageFat
age<-bodyfatdata$Age
weight<-bodyfatdata$Weight
height<-bodyfatdata$Height
neck<-bodyfatdata$Neck
chest<-bodyfatdata$Chest
abdomen<-bodyfatdata$Abdom
hip<-bodyfatdata$Hip
thigh<-bodyfatdata$Thigh
knee<-bodyfatdata$Knee
ankle<-bodyfatdata$Ankle
biceps<-bodyfatdata$Biceps
forearm<-bodyfatdata$Forearm
wrist<-bodyfatdata$Wrist
predictors<-data.frame(age,weight,height,neck,chest,abdomen,hip,thigh,knee,ankle,biceps,forearm,wrist)
bodyfatmodel<-lm(percentageFat~weight+age+height+neck+chest+abdomen+hip+thigh+knee+ankle+biceps+forearm+wrist)

